<a href="https://colab.research.google.com/github/natalia-maler/Housing_price_prediction_using_neural_networks_and_Random_Forest/blob/main/Housing_price_prediction_using_neural_networks_and_Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Celem projektu było zbudowanie modeli regresyjnych przewidujących medianę cen mieszkań na podstawie cech demograficznych i geograficznych pochodzących ze zbioru California Housing. W projekcie porównano skuteczność prostego modelu sieci neuronowej, ulepszonej sieci neuronowej oraz modelu Random Forest ze strojeniem hiperparametrów.

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

np.set_printoptions(precision=12, suppress=True, linewidth=150) # 12 miejsc po przecinku, suppress bez notacji naukowej, linewidth szerokość wyświetlania
pd.options.display.float_format = '{:.6f}'.format
tf.__version__

'2.20.0'

In [2]:
# dane - chmura google cloud
url = "https://storage.googleapis.com/esmartdata-courses-files/ann-course/housing.csv"
df = pd.read_csv(url)
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.230000,37.880000,41.000000,880.000000,129.000000,322.000000,126.000000,8.325200,452600.000000,NEAR BAY
1,-122.220000,37.860000,21.000000,7099.000000,1106.000000,2401.000000,1138.000000,8.301400,358500.000000,NEAR BAY
2,-122.240000,37.850000,52.000000,1467.000000,190.000000,496.000000,177.000000,7.257400,352100.000000,NEAR BAY
3,-122.250000,37.850000,52.000000,1274.000000,235.000000,558.000000,219.000000,5.643100,341300.000000,NEAR BAY
4,-122.250000,37.850000,52.000000,1627.000000,280.000000,565.000000,259.000000,3.846200,342200.000000,NEAR BAY

Wyjaśnienie kolumn

Zbiór danych California Housing pochodzi z amerykańskiego spisu ludności i zawiera informacje o warunkach mieszkaniowych w różnych regionach Kalifornii.
Celem zadania jest przewidywanie mediany wartości domu (median_house_value) na podstawie cech demograficznych i geograficznych danego obszaru.

- longitude - długość geograficzna, położenie w kierunku wschód-zachód.
- latitude - szerokość geograficzna, położenie w kierunku południe-półudnie.
- housing_median_age - mediana wieku budynków w okolicy.
- total_rooms - łączna liczba pokoi w danym obszarze, a nie jednego domu.
- total_bedrooms - liczba sypialni, a nie jednego domu.
- population - liczba mieszkańców.
- households - liczba gospodarstw domowych.
- median_income - mediana dochodu gospodarstw domowych, w dziesiątkach tysięcy USD: 8.3252 ~ 83 252 USD.
- ocean_proximity - położenie względem oceanu, zmienna tekstowa np. INLAND - daleko od oceanu, NEAR BAY - blisko zatoki .
- median_house_value - wartość domu, zmienna przewidywana.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [4]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [5]:
df.isnull().sum() / len(df)

longitude            0.000000
latitude             0.000000
housing_median_age   0.000000
total_rooms          0.000000
total_bedrooms       0.010029
population           0.000000
households           0.000000
median_income        0.000000
median_house_value   0.000000
ocean_proximity      0.000000
dtype: float64

In [6]:
df = df.dropna()
# usuniecie braków, gdzie wystepują

In [7]:
df.isnull().sum() / len(df)

longitude            0.000000
latitude             0.000000
housing_median_age   0.000000
total_rooms          0.000000
total_bedrooms       0.000000
population           0.000000
households           0.000000
median_income        0.000000
median_house_value   0.000000
ocean_proximity      0.000000
dtype: float64

In [8]:
df.describe(include=['object'])

       ocean_proximity
count            20433
unique               5
top          <1H OCEAN
freq              9034

In [9]:
df.ocean_proximity.value_counts()

ocean_proximity
<1H OCEAN     9034
INLAND        6496
NEAR OCEAN    2628
NEAR BAY      2270
ISLAND           5
Name: count, dtype: int64

In [10]:
# wykres korelacji
px.scatter(df, x="median_income", y="median_house_value", title="Income vs House Value")

In [11]:
# rozkład zmiennej docelowej median_house_value
px.histogram(df, x='median_house_value')

In [12]:
df.median_house_value.value_counts()

median_house_value
500001.000000    958
137500.000000    119
162500.000000    116
112500.000000    103
187500.000000     92
                ...
321700.000000      1
300800.000000      1
393100.000000      1
203600.000000      1
374600.000000      1
Name: count, Length: 3833, dtype: int64

In [13]:
# pozostawienie tylko normalnych cen domów, usuniecie sztucznych 500001
df = df[df["median_house_value"] < 500001]

In [14]:
px.histogram(df, x='median_house_value')

In [15]:
df.median_house_value.value_counts()

median_house_value
137500.000000    119
162500.000000    116
112500.000000    103
187500.000000     92
225000.000000     91
                ...
46200.000000       1
385200.000000      1
358200.000000      1
303200.000000      1
299700.000000      1
Name: count, Length: 3832, dtype: int64

In [16]:
# zakodowanie kategorycznych kategorii(teskstowych)
df = pd.get_dummies(df, drop_first=True)
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.230000,37.880000,41.000000,880.000000,129.000000,322.000000,126.000000,8.325200,452600.000000,False,False,True,False
1,-122.220000,37.860000,21.000000,7099.000000,1106.000000,2401.000000,1138.000000,8.301400,358500.000000,False,False,True,False
2,-122.240000,37.850000,52.000000,1467.000000,190.000000,496.000000,177.000000,7.257400,352100.000000,False,False,True,False
3,-122.250000,37.850000,52.000000,1274.000000,235.000000,558.000000,219.000000,5.643100,341300.000000,False,False,True,False
4,-122.250000,37.850000,52.000000,1627.000000,280.000000,565.000000,259.000000,3.846200,342200.000000,False,False,True,False

In [17]:
# Zamiana bool na int 0/1
bool_cols = df.select_dtypes(include='bool').columns

df[bool_cols] = df[bool_cols].astype(int)

In [18]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.230000,37.880000,41.000000,880.000000,129.000000,322.000000,126.000000,8.325200,452600.000000,0,0,1,0
1,-122.220000,37.860000,21.000000,7099.000000,1106.000000,2401.000000,1138.000000,8.301400,358500.000000,0,0,1,0
2,-122.240000,37.850000,52.000000,1467.000000,190.000000,496.000000,177.000000,7.257400,352100.000000,0,0,1,0
3,-122.250000,37.850000,52.000000,1274.000000,235.000000,558.000000,219.000000,5.643100,341300.000000,0,0,1,0
4,-122.250000,37.850000,52.000000,1627.000000,280.000000,565.000000,259.000000,3.846200,342200.000000,0,0,1,0

In [19]:
X = df.drop("median_house_value", axis=1)
y = df["median_house_value"]

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
print(f'X_train shape: {X_train.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'y_test shape: {y_test.shape}')

X_train shape: (15580, 12)
y_train shape: (15580,)
X_test shape: (3895, 12)
y_test shape: (3895,)

In [22]:
X_train.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
5148,-118.270000,33.970000,34.000000,1462.000000,394.000000,1310.000000,351.000000,1.155700,0,0,0,0
1378,-122.100000,38.020000,28.000000,4308.000000,824.000000,2086.000000,776.000000,3.652300,0,0,1,0
10567,-117.740000,33.730000,18.000000,328.000000,68.000000,391.000000,60.000000,4.116700,0,0,0,0
16253,-121.270000,37.960000,52.000000,583.000000,114.000000,310.000000,93.000000,2.562500,1,0,0,0
3920,-118.560000,34.200000,36.000000,1544.000000,308.000000,891.000000,286.000000,4.175000,0,0,0,0

In [23]:
y_train.head()

5148     90100.000000
1378    159700.000000
10567    87500.000000
16253    54200.000000
3920    190900.000000
Name: median_house_value, dtype: float64

standaryzacja

In [24]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
y_scaler = StandardScaler()

y_train = y_scaler.fit_transform(y_train.values.reshape(-1,1))
y_test = y_scaler.transform(y_test.values.reshape(-1,1))

In [26]:
X_train

array([[ 0.652101226036, -0.788944225811,  0.452039473674, ..., -0.017917234366, -0.35181501198 , -0.372789682109],
       [-1.257708150263,  1.095295386106, -0.027724485533, ..., -0.017917234366,  2.842402870681, -0.372789682109],
       [ 0.916382941294, -0.90060286948 , -0.827331084211, ..., -0.017917234366, -0.35181501198 , -0.372789682109],
       ...,
       [ 0.667060568409, -0.663328251683,  0.21215749407 , ..., -0.017917234366, -0.35181501198 , -0.372789682109],
       [-1.212830123144,  0.88128298574 , -1.786859002625, ..., -0.017917234366,  2.842402870681, -0.372789682109],
       [-0.539659716354, -0.216693677007, -1.22713438355 , ..., -0.017917234366, -0.35181501198 ,  2.682477675732]])

In [27]:
df[
[
'ocean_proximity_INLAND',
'ocean_proximity_ISLAND',
'ocean_proximity_NEAR BAY',
'ocean_proximity_NEAR OCEAN'
]
].sum()

ocean_proximity_INLAND        6469
ocean_proximity_ISLAND           5
ocean_proximity_NEAR BAY      2077
ocean_proximity_NEAR OCEAN    2419
dtype: int64

In [28]:
import tensorflow as tf

def r2_score(y_true, y_pred):
    ss_res = tf.reduce_sum(tf.square(y_true - y_pred))
    ss_tot = tf.reduce_sum(tf.square(y_true - tf.reduce_mean(y_true)))
    return 1 - ss_res / (ss_tot + tf.keras.backend.epsilon())

budowa modelu - prosty model

In [29]:
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mse', metrics=['mae', 'mse',r2_score])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

In [31]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
history = model.fit(X_train, y_train, epochs=30, validation_split=0.2, verbose=1, batch_size=32)

Epoch 1/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.4260 - mae: 0.4677 - mse: 0.4260 - r2_score: 0.5599 - val_loss: 0.3265 - val_mae: 0.4123 - val_mse: 0.3265 - val_r2_score: 0.6495
Epoch 2/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3418 - mae: 0.4130 - mse: 0.3418 - r2_score: 0.6435 - val_loss: 0.3065 - val_mae: 0.3896 - val_mse: 0.3065 - val_r2_score: 0.6707
Epoch 3/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3153 - mae: 0.3982 - mse: 0.3153 - r2_score: 0.6689 - val_loss: 0.3061 - val_mae: 0.3974 - val_mse: 0.3061 - val_r2_score: 0.6677
Epoch 4/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3210 - mae: 0.3924 - mse: 0.3210 - r2_score: 0.6620 - val_loss: 0.2984 - val_mae: 0.3940 - val_mse: 0.2984 - val_r2_score: 0.6762
Epoch 5/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.2968 - mae: 0.3842 - mse: 0.2968 - r2_score: 0.6903 - val_loss: 0.2884 - val_mae: 0.3836 - val_mse: 0.2884 - val_r2_score: 0.6895
Epoch 6/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2889 - mae: 0.3794 - mse: 0.2889 - r2_score: 0.6920 - val_loss: 0.2822 - val_mae: 0.3724 - val_mse: 0.2822 - val_r2_score: 0.6971
Epoch 7/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2839 - mae: 0.3755 - mse: 0.2839 - r2_score: 0.7006 - val_loss: 0.2789 - val_mae: 0.3707 - val_mse: 0.2789 - val_r2_score: 0.6991
Epoch 8/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2788 - mae: 0.3714 - mse: 0.2788 - r2_score: 0.7053 - val_loss: 0.2853 - val_mae: 0.3869 - val_mse: 0.2853 - val_r2_score: 0.6895
Epoch 9/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2834 - mae: 0.3714 - mse: 0.2834 - r2_score: 0.7067 - val_loss: 0.2745 - val_mae: 0.3660 - val_mse: 0.2745 - val_r2_score: 0.7002
Epoch 10/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2763 - mae: 0.3662 - mse: 0.2763 - r2_score: 0.7096 - val_loss: 0.2730 - val_mae: 0.3661 - val_mse: 0.2730 - val_r2_score: 0.7058
Epoch 11/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2701 - mae: 0.3644 - mse: 0.2701 - r2_score: 0.7162 - val_loss: 0.2705 - val_mae: 0.3674 - val_mse: 0.2705 - val_r2_score: 0.7047
Epoch 12/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2681 - mae: 0.3621 - mse: 0.2681 - r2_score: 0.7204 - val_loss: 0.2683 - val_mae: 0.3678 - val_mse: 0.2683 - val_r2_score: 0.7103
Epoch 13/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2648 - mae: 0.3603 - mse: 0.2648 - r2_score: 0.7210 - val_loss: 0.2651 - val_mae: 0.3623 - val_mse: 0.2651 - val_r2_score: 0.7118
Epoch 14/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2615 - mae: 0.3572 - mse: 0.2615 - r2_score: 0.7234 - val_loss: 0.2687 - val_mae: 0.3675 - val_mse: 0.2687 - val_r2_score: 0.7090
Epoch 15/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2582 - mae: 0.3556 - mse: 0.2582 - r2_score: 0.7279 - val_loss: 0.2639 - val_mae: 0.3658 - val_mse: 0.2639 - val_r2_score: 0.7172
Epoch 16/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2563 - mae: 0.3544 - mse: 0.2563 - r2_score: 0.7309 - val_loss: 0.2629 - val_mae: 0.3557 - val_mse: 0.2629 - val_r2_score: 0.7155
Epoch 17/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2535 - mae: 0.3521 - mse: 0.2535 - r2_score: 0.7342 - val_loss: 0.2566 - val_mae: 0.3495 - val_mse: 0.2566 - val_r2_score: 0.7223
Epoch 18/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2523 - mae: 0.3508 - mse: 0.2523 - r2_score: 0.7343 - val_loss: 0.2649 - val_mae: 0.3607 - val_mse: 0.2649 - val_r2_score: 0.7088
Epoch 19/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2528 - mae: 0.3516 - mse: 0.2528 - r2_score: 0.7349 - val_loss: 0.2548 - val_mae: 0.3463 - val_mse: 0.2548 - val_r2_score: 0.7255
Epoch 20/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2472 - mae: 0.3472 - mse: 0.2472 - r2_score: 0.7412 - val_loss: 0.2517 - val_mae: 0.3500 - val_mse: 0.2517 - val_r2_score: 0.7281
Epoch 21/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2496 - mae: 0.3488 - mse: 0.2496 - r2_score: 0.7355 - val_loss: 0.2513 - val_mae: 0.3487 - val_mse: 0.2513 - val_r2_score: 0.7280
Epoch 22/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2450 - mae: 0.3458 - mse: 0.2450 - r2_score: 0.7411 - val_loss: 0.2521 - val_mae: 0.3596 - val_mse: 0.2521 - val_r2_score: 0.7280
Epoch 23/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2446 - mae: 0.3448 - mse: 0.2446 - r2_score: 0.7412 - val_loss: 0.2538 - val_mae: 0.3593 - val_mse: 0.2538 - val_r2_score: 0.7221
Epoch 24/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2438 - mae: 0.3443 - mse: 0.2438 - r2_score: 0.7430 - val_loss: 0.2484 - val_mae: 0.3472 - val_mse: 0.2484 - val_r2_score: 0.7331
Epoch 25/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2410 - mae: 0.3425 - mse: 0.2410 - r2_score: 0.7475 - val_loss: 0.2509 - val_mae: 0.3493 - val_mse: 0.2509 - val_r2_score: 0.7270
Epoch 26/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2421 - mae: 0.3439 - mse: 0.2421 - r2_score: 0.7409 - val_loss: 0.2480 - val_mae: 0.3480 - val_mse: 0.2480 - val_r2_score: 0.7342
Epoch 27/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2401 - mae: 0.3411 - mse: 0.2401 - r2_score: 0.7478 - val_loss: 0.2500 - val_mae: 0.3555 - val_mse: 0.2500 - val_r2_score: 0.7280
Epoch 28/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2367 - mae: 0.3394 - mse: 0.2367 - r2_score: 0.7532 - val_loss: 0.2434 - val_mae: 0.3441 - val_mse: 0.2434 - val_r2_score: 0.7342
Epoch 29/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2371 - mae: 0.3393 - mse: 0.2371 - r2_score: 0.7517 - val_loss: 0.2464 - val_mae: 0.3485 - val_mse: 0.2464 - val_r2_score: 0.7324
Epoch 30/30
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2340 - mae: 0.3361 - mse: 0.2340 - r2_score: 0.7517 - val_loss: 0.2414 - val_mae: 0.3428 - val_mse: 0.2414 - val_r2_score: 0.7406

In [33]:
def plot_hist(history):
    hist = pd.DataFrame(history.history)
    hist['epoch'] = history.epoch
    hist['rmse'] = np.sqrt(hist['mse'])

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=hist['epoch'], y=hist['mae'], name='mae', mode='markers+lines'))
    fig.add_trace(go.Scatter(x=hist['epoch'], y=hist['val_mae'], name='val_mae', mode='markers+lines'))
    fig.update_layout(width=1000, height=500, title='MAE vs. VAL_MAE', xaxis_title='Epoki', yaxis_title='Mean Absolute Error', yaxis_type='log')
    fig.show()

plot_hist(history)

In [34]:
test_loss, test_mae, _, _ = model.evaluate(X_test, y_test)

print("Test MSE:", test_loss)
print("Test MAE:", test_mae)

122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2539 - mae: 0.3516 - mse: 0.2539 - r2_score: 0.7383
Test MSE: 0.2539239525794983
Test MAE: 0.351639986038208

In [35]:
from sklearn.metrics import r2_score

predictions = model.predict(X_test)

r2 = r2_score(y_test, predictions)
print("R2:", r2)

122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
R2: 0.7506675623979435

In [36]:
# poprawa danych - cofniecie skalowania
predictions = model.predict(X_test).flatten()

# cofnięcie skalowania
predictions_real = y_scaler.inverse_transform(predictions.reshape(-1,1)).flatten()
y_test_real = y_scaler.inverse_transform(y_test).flatten()

results = pd.DataFrame({
  "rzeczywiste": y_test_real,
  "przewidywane": predictions_real,
   "błąd": abs(predictions_real - y_test_real)
})

results.head()

122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

    rzeczywiste  przewidywane         błąd
0  96200.000000 104314.367188  8114.367188
1 178700.000000 196943.250000 18243.250000
2  60600.000000  68090.320312  7490.320312
3 191900.000000 176061.703125 15838.296875
4  51000.000000  61591.539062 10591.539062

In [37]:
fig = px.scatter(results, x='rzeczywiste', y='przewidywane')
fig.add_trace(go.Scatter(x=[0, 500000], y=[0, 500000], mode='lines'))
fig.show()

In [38]:
px.histogram(results, x='błąd', marginal='rug', width=1000)

ulepszony model: BatchNormalization(), Dropout(), earlyStopping(), learning_rate

In [39]:
from tensorflow.keras.regularizers import l2
model = Sequential()
model.add(Dense(128, activation='relu',kernel_regularizer=l2(0.001), input_shape=(X_train.shape[1],)))
model.add(BatchNormalization())
model.add(Dropout(0.3))
model.add(Dense(64,kernel_regularizer=l2(0.001), activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))
model.add(Dense(32,kernel_regularizer=l2(0.001), activation='relu'))
model.add(BatchNormalization())
model.add(Dense(1))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

In [40]:
from tensorflow.keras.callbacks import ReduceLROnPlateau
lr_scheduler = ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=5, min_lr=1e-6)

In [41]:
# interpretacja wskażnika R2
def r2_score(y_true, y_pred):
    ss_res = tf.reduce_sum(tf.square(y_true - y_pred))
    ss_tot = tf.reduce_sum(tf.square(y_true - tf.reduce_mean(y_true)))
    return 1 - ss_res / (ss_tot + tf.keras.backend.epsilon())

In [42]:
model.compile(optimizer=tf.keras.optimizers.AdamW(learning_rate=0.001, weight_decay=1e-4), loss='mse', metrics=['mae', 'mse',r2_score])

In [43]:
early_stop = EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True)

In [44]:
history = model.fit(X_train, y_train, epochs=100, validation_split=0.2, verbose=1, batch_size=32, callbacks=[early_stop, lr_scheduler])

Epoch 1/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 0.8579 - mae: 0.6311 - mse: 0.7106 - r2_score: 0.2381 - val_loss: 0.5377 - val_mae: 0.4848 - val_mse: 0.3928 - val_r2_score: 0.5780 - learning_rate: 0.0010
Epoch 2/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.6140 - mae: 0.5115 - mse: 0.4723 - r2_score: 0.4921 - val_loss: 0.4675 - val_mae: 0.4166 - val_mse: 0.3292 - val_r2_score: 0.6494 - learning_rate: 0.0010
Epoch 3/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.5518 - mae: 0.4784 - mse: 0.4174 - r2_score: 0.5576 - val_loss: 0.4425 - val_mae: 0.3985 - val_mse: 0.3123 - val_r2_score: 0.6645 - learning_rate: 0.0010
Epoch 4/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 0.5149 - mae: 0.4577 - mse: 0.3893 - r2_score: 0.5872 - val_loss: 0.4218 - val_mae: 0.3913 - val_mse: 0.3007 - val_r2_score: 0.6787 - learning_rate: 0.0010
Epoch 5/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.4903 - mae: 0.4464 - mse: 0.3740 - r2_score: 0.6019 - val_loss: 0.4081 - val_mae: 0.3875 - val_mse: 0.2967 - val_r2_score: 0.6817 - learning_rate: 0.0010
Epoch 6/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4698 - mae: 0.4426 - mse: 0.3633 - r2_score: 0.6134 - val_loss: 0.3924 - val_mae: 0.3797 - val_mse: 0.2909 - val_r2_score: 0.6897 - learning_rate: 0.0010
Epoch 7/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4494 - mae: 0.4316 - mse: 0.3526 - r2_score: 0.6287 - val_loss: 0.3734 - val_mae: 0.3758 - val_mse: 0.2813 - val_r2_score: 0.6972 - learning_rate: 0.0010
Epoch 8/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4391 - mae: 0.4306 - mse: 0.3518 - r2_score: 0.6185 - val_loss: 0.3697 - val_mae: 0.3826 - val_mse: 0.2869 - val_r2_score: 0.6889 - learning_rate: 0.0010
Epoch 9/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4166 - mae: 0.4236 - mse: 0.3379 - r2_score: 0.6419 - val_loss: 0.3500 - val_mae: 0.3700 - val_mse: 0.2753 - val_r2_score: 0.7034 - learning_rate: 0.0010
Epoch 10/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4073 - mae: 0.4208 - mse: 0.3364 - r2_score: 0.6446 - val_loss: 0.3549 - val_mae: 0.3789 - val_mse: 0.2876 - val_r2_score: 0.6899 - learning_rate: 0.0010
Epoch 11/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4013 - mae: 0.4202 - mse: 0.3371 - r2_score: 0.6440 - val_loss: 0.3310 - val_mae: 0.3672 - val_mse: 0.2699 - val_r2_score: 0.7091 - learning_rate: 0.0010
Epoch 12/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3870 - mae: 0.4170 - mse: 0.3287 - r2_score: 0.6494 - val_loss: 0.3250 - val_mae: 0.3595 - val_mse: 0.2696 - val_r2_score: 0.7113 - learning_rate: 0.0010
Epoch 13/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.3877 - mae: 0.4181 - mse: 0.3347 - r2_score: 0.6396 - val_loss: 0.3201 - val_mae: 0.3548 - val_mse: 0.2694 - val_r2_score: 0.7095 - learning_rate: 0.0010
Epoch 14/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.3844 - mae: 0.4181 - mse: 0.3356 - r2_score: 0.6355 - val_loss: 0.3097 - val_mae: 0.3545 - val_mse: 0.2628 - val_r2_score: 0.7168 - learning_rate: 0.0010
Epoch 15/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3681 - mae: 0.4107 - mse: 0.3230 - r2_score: 0.6541 - val_loss: 0.3229 - val_mae: 0.3781 - val_mse: 0.2793 - val_r2_score: 0.7030 - learning_rate: 0.0010
Epoch 16/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3621 - mae: 0.4071 - mse: 0.3198 - r2_score: 0.6629 - val_loss: 0.3102 - val_mae: 0.3666 - val_mse: 0.2691 - val_r2_score: 0.7115 - learning_rate: 0.0010
Epoch 17/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.3663 - mae: 0.4138 - mse: 0.3263 - r2_score: 0.6516 - val_loss: 0.2991 - val_mae: 0.3544 - val_mse: 0.2602 - val_r2_score: 0.7214 - learning_rate: 0.0010
Epoch 18/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3561 - mae: 0.4073 - mse: 0.3182 - r2_score: 0.6635 - val_loss: 0.3007 - val_mae: 0.3661 - val_mse: 0.2637 - val_r2_score: 0.7176 - learning_rate: 0.0010
Epoch 19/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3542 - mae: 0.4064 - mse: 0.3179 - r2_score: 0.6665 - val_loss: 0.3030 - val_mae: 0.3657 - val_mse: 0.2674 - val_r2_score: 0.7112 - learning_rate: 0.0010
Epoch 20/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.3567 - mae: 0.4112 - mse: 0.3216 - r2_score: 0.6528 - val_loss: 0.3026 - val_mae: 0.3699 - val_mse: 0.2680 - val_r2_score: 0.7120 - learning_rate: 0.0010
Epoch 21/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.3476 - mae: 0.4025 - mse: 0.3134 - r2_score: 0.6675 - val_loss: 0.2908 - val_mae: 0.3604 - val_mse: 0.2572 - val_r2_score: 0.7239 - learning_rate: 0.0010
Epoch 22/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 0.3506 - mae: 0.4067 - mse: 0.3172 - r2_score: 0.6601 - val_loss: 0.2810 - val_mae: 0.3438 - val_mse: 0.2482 - val_r2_score: 0.7312 - learning_rate: 0.0010
Epoch 23/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.3419 - mae: 0.4016 - mse: 0.3096 - r2_score: 0.6703 - val_loss: 0.2936 - val_mae: 0.3563 - val_mse: 0.2618 - val_r2_score: 0.7170 - learning_rate: 0.0010
Epoch 24/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3455 - mae: 0.4046 - mse: 0.3140 - r2_score: 0.6655 - val_loss: 0.2889 - val_mae: 0.3527 - val_mse: 0.2576 - val_r2_score: 0.7219 - learning_rate: 0.0010
Epoch 25/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3397 - mae: 0.4004 - mse: 0.3085 - r2_score: 0.6753 - val_loss: 0.2907 - val_mae: 0.3665 - val_mse: 0.2599 - val_r2_score: 0.7199 - learning_rate: 0.0010
Epoch 26/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3494 - mae: 0.4085 - mse: 0.3187 - r2_score: 0.6591 - val_loss: 0.2942 - val_mae: 0.3589 - val_mse: 0.2635 - val_r2_score: 0.7174 - learning_rate: 0.0010
Epoch 27/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.3400 - mae: 0.4016 - mse: 0.3095 - r2_score: 0.6697 - val_loss: 0.2841 - val_mae: 0.3524 - val_mse: 0.2536 - val_r2_score: 0.7265 - learning_rate: 0.0010
Epoch 28/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.3308 - mae: 0.3948 - mse: 0.3009 - r2_score: 0.6780 - val_loss: 0.2690 - val_mae: 0.3406 - val_mse: 0.2397 - val_r2_score: 0.7396 - learning_rate: 5.0000e-04
Epoch 29/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3248 - mae: 0.3924 - mse: 0.2960 - r2_score: 0.6838 - val_loss: 0.2675 - val_mae: 0.3419 - val_mse: 0.2391 - val_r2_score: 0.7404 - learning_rate: 5.0000e-04
Epoch 30/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3179 - mae: 0.3869 - mse: 0.2900 - r2_score: 0.6875 - val_loss: 0.2620 - val_mae: 0.3355 - val_mse: 0.2345 - val_r2_score: 0.7470 - learning_rate: 5.0000e-04
Epoch 31/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3227 - mae: 0.3908 - mse: 0.2956 - r2_score: 0.6855 - val_loss: 0.2566 - val_mae: 0.3338 - val_mse: 0.2299 - val_r2_score: 0.7512 - learning_rate: 5.0000e-04
Epoch 32/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3216 - mae: 0.3921 - mse: 0.2951 - r2_score: 0.6827 - val_loss: 0.2607 - val_mae: 0.3373 - val_mse: 0.2345 - val_r2_score: 0.7438 - learning_rate: 5.0000e-04
Epoch 33/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3125 - mae: 0.3842 - mse: 0.2866 - r2_score: 0.6954 - val_loss: 0.2581 - val_mae: 0.3332 - val_mse: 0.2326 - val_r2_score: 0.7479 - learning_rate: 5.0000e-04
Epoch 34/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3126 - mae: 0.3848 - mse: 0.2873 - r2_score: 0.6959 - val_loss: 0.2552 - val_mae: 0.3354 - val_mse: 0.2300 - val_r2_score: 0.7504 - learning_rate: 5.0000e-04
Epoch 35/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3111 - mae: 0.3824 - mse: 0.2861 - r2_score: 0.6978 - val_loss: 0.2652 - val_mae: 0.3433 - val_mse: 0.2403 - val_r2_score: 0.7420 - learning_rate: 5.0000e-04
Epoch 36/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.3138 - mae: 0.3882 - mse: 0.2891 - r2_score: 0.6895 - val_loss: 0.2645 - val_mae: 0.3410 - val_mse: 0.2399 - val_r2_score: 0.7401 - learning_rate: 5.0000e-04
Epoch 37/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.3088 - mae: 0.3836 - mse: 0.2843 - r2_score: 0.6925 - val_loss: 0.2621 - val_mae: 0.3369 - val_mse: 0.2378 - val_r2_score: 0.7424 - learning_rate: 5.0000e-04
Epoch 38/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3115 - mae: 0.3838 - mse: 0.2873 - r2_score: 0.6950 - val_loss: 0.2599 - val_mae: 0.3440 - val_mse: 0.2359 - val_r2_score: 0.7440 - learning_rate: 5.0000e-04
Epoch 39/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3091 - mae: 0.3841 - mse: 0.2852 - r2_score: 0.6930 - val_loss: 0.2538 - val_mae: 0.3286 - val_mse: 0.2300 - val_r2_score: 0.7498 - learning_rate: 5.0000e-04
Epoch 40/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3040 - mae: 0.3783 - mse: 0.2803 - r2_score: 0.7017 - val_loss: 0.2576 - val_mae: 0.3365 - val_mse: 0.2339 - val_r2_score: 0.7497 - learning_rate: 5.0000e-04
Epoch 41/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3071 - mae: 0.3808 - mse: 0.2835 - r2_score: 0.7020 - val_loss: 0.2538 - val_mae: 0.3354 - val_mse: 0.2303 - val_r2_score: 0.7483 - learning_rate: 5.0000e-04
Epoch 42/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3050 - mae: 0.3811 - mse: 0.2815 - r2_score: 0.7001 - val_loss: 0.2523 - val_mae: 0.3316 - val_mse: 0.2290 - val_r2_score: 0.7528 - learning_rate: 5.0000e-04
Epoch 43/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3091 - mae: 0.3853 - mse: 0.2859 - r2_score: 0.6907 - val_loss: 0.2581 - val_mae: 0.3348 - val_mse: 0.2349 - val_r2_score: 0.7470 - learning_rate: 5.0000e-04
Epoch 44/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3077 - mae: 0.3830 - mse: 0.2846 - r2_score: 0.6972 - val_loss: 0.2480 - val_mae: 0.3283 - val_mse: 0.2250 - val_r2_score: 0.7560 - learning_rate: 5.0000e-04
Epoch 45/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.3004 - mae: 0.3773 - mse: 0.2773 - r2_score: 0.7071 - val_loss: 0.2526 - val_mae: 0.3339 - val_mse: 0.2296 - val_r2_score: 0.7514 - learning_rate: 5.0000e-04
Epoch 46/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3083 - mae: 0.3854 - mse: 0.2854 - r2_score: 0.6915 - val_loss: 0.2487 - val_mae: 0.3358 - val_mse: 0.2258 - val_r2_score: 0.7562 - learning_rate: 5.0000e-04
Epoch 47/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3016 - mae: 0.3787 - mse: 0.2789 - r2_score: 0.7002 - val_loss: 0.2460 - val_mae: 0.3265 - val_mse: 0.2234 - val_r2_score: 0.7572 - learning_rate: 5.0000e-04
Epoch 48/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3020 - mae: 0.3798 - mse: 0.2794 - r2_score: 0.7009 - val_loss: 0.2455 - val_mae: 0.3309 - val_mse: 0.2229 - val_r2_score: 0.7589 - learning_rate: 5.0000e-04
Epoch 49/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3039 - mae: 0.3813 - mse: 0.2813 - r2_score: 0.6990 - val_loss: 0.2461 - val_mae: 0.3272 - val_mse: 0.2236 - val_r2_score: 0.7565 - learning_rate: 5.0000e-04
Epoch 50/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3060 - mae: 0.3804 - mse: 0.2835 - r2_score: 0.6987 - val_loss: 0.2416 - val_mae: 0.3255 - val_mse: 0.2192 - val_r2_score: 0.7618 - learning_rate: 5.0000e-04
Epoch 51/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2962 - mae: 0.3765 - mse: 0.2739 - r2_score: 0.7078 - val_loss: 0.2464 - val_mae: 0.3344 - val_mse: 0.2242 - val_r2_score: 0.7557 - learning_rate: 5.0000e-04
Epoch 52/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2983 - mae: 0.3764 - mse: 0.2761 - r2_score: 0.7057 - val_loss: 0.2523 - val_mae: 0.3398 - val_mse: 0.2301 - val_r2_score: 0.7500 - learning_rate: 5.0000e-04
Epoch 53/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3001 - mae: 0.3765 - mse: 0.2780 - r2_score: 0.7037 - val_loss: 0.2531 - val_mae: 0.3317 - val_mse: 0.2309 - val_r2_score: 0.7499 - learning_rate: 5.0000e-04
Epoch 54/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.3019 - mae: 0.3821 - mse: 0.2798 - r2_score: 0.7008 - val_loss: 0.2444 - val_mae: 0.3285 - val_mse: 0.2222 - val_r2_score: 0.7570 - learning_rate: 5.0000e-04
Epoch 55/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3027 - mae: 0.3798 - mse: 0.2805 - r2_score: 0.6992 - val_loss: 0.2419 - val_mae: 0.3265 - val_mse: 0.2198 - val_r2_score: 0.7610 - learning_rate: 5.0000e-04
Epoch 56/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2936 - mae: 0.3742 - mse: 0.2716 - r2_score: 0.7106 - val_loss: 0.2381 - val_mae: 0.3213 - val_mse: 0.2162 - val_r2_score: 0.7661 - learning_rate: 2.5000e-04
Epoch 57/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2950 - mae: 0.3727 - mse: 0.2733 - r2_score: 0.7042 - val_loss: 0.2352 - val_mae: 0.3160 - val_mse: 0.2136 - val_r2_score: 0.7686 - learning_rate: 2.5000e-04
Epoch 58/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2945 - mae: 0.3759 - mse: 0.2730 - r2_score: 0.7070 - val_loss: 0.2381 - val_mae: 0.3213 - val_mse: 0.2168 - val_r2_score: 0.7648 - learning_rate: 2.5000e-04
Epoch 59/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2893 - mae: 0.3701 - mse: 0.2681 - r2_score: 0.7168 - val_loss: 0.2359 - val_mae: 0.3176 - val_mse: 0.2148 - val_r2_score: 0.7661 - learning_rate: 2.5000e-04
Epoch 60/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2788 - mae: 0.3643 - mse: 0.2579 - r2_score: 0.7281 - val_loss: 0.2371 - val_mae: 0.3206 - val_mse: 0.2163 - val_r2_score: 0.7671 - learning_rate: 2.5000e-04
Epoch 61/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2872 - mae: 0.3726 - mse: 0.2665 - r2_score: 0.7121 - val_loss: 0.2318 - val_mae: 0.3179 - val_mse: 0.2111 - val_r2_score: 0.7717 - learning_rate: 2.5000e-04
Epoch 62/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2818 - mae: 0.3657 - mse: 0.2613 - r2_score: 0.7222 - val_loss: 0.2341 - val_mae: 0.3180 - val_mse: 0.2137 - val_r2_score: 0.7680 - learning_rate: 2.5000e-04
Epoch 63/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.2840 - mae: 0.3691 - mse: 0.2637 - r2_score: 0.7136 - val_loss: 0.2322 - val_mae: 0.3178 - val_mse: 0.2119 - val_r2_score: 0.7696 - learning_rate: 2.5000e-04
Epoch 64/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2842 - mae: 0.3683 - mse: 0.2640 - r2_score: 0.7148 - val_loss: 0.2362 - val_mae: 0.3222 - val_mse: 0.2161 - val_r2_score: 0.7669 - learning_rate: 2.5000e-04
Epoch 65/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2785 - mae: 0.3648 - mse: 0.2585 - r2_score: 0.7242 - val_loss: 0.2290 - val_mae: 0.3164 - val_mse: 0.2091 - val_r2_score: 0.7715 - learning_rate: 2.5000e-04
Epoch 66/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2851 - mae: 0.3699 - mse: 0.2652 - r2_score: 0.7168 - val_loss: 0.2299 - val_mae: 0.3144 - val_mse: 0.2101 - val_r2_score: 0.7721 - learning_rate: 2.5000e-04
Epoch 67/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2803 - mae: 0.3675 - mse: 0.2606 - r2_score: 0.7199 - val_loss: 0.2329 - val_mae: 0.3179 - val_mse: 0.2132 - val_r2_score: 0.7688 - learning_rate: 2.5000e-04
Epoch 68/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2803 - mae: 0.3662 - mse: 0.2607 - r2_score: 0.7219 - val_loss: 0.2311 - val_mae: 0.3162 - val_mse: 0.2116 - val_r2_score: 0.7694 - learning_rate: 2.5000e-04
Epoch 69/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2859 - mae: 0.3693 - mse: 0.2664 - r2_score: 0.7150 - val_loss: 0.2318 - val_mae: 0.3145 - val_mse: 0.2124 - val_r2_score: 0.7696 - learning_rate: 2.5000e-04
Epoch 70/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2841 - mae: 0.3700 - mse: 0.2647 - r2_score: 0.7129 - val_loss: 0.2321 - val_mae: 0.3197 - val_mse: 0.2128 - val_r2_score: 0.7686 - learning_rate: 2.5000e-04
Epoch 71/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.2741 - mae: 0.3633 - mse: 0.2548 - r2_score: 0.7216 - val_loss: 0.2262 - val_mae: 0.3117 - val_mse: 0.2070 - val_r2_score: 0.7751 - learning_rate: 1.2500e-04
Epoch 72/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.2764 - mae: 0.3644 - mse: 0.2573 - r2_score: 0.7247 - val_loss: 0.2298 - val_mae: 0.3168 - val_mse: 0.2107 - val_r2_score: 0.7713 - learning_rate: 1.2500e-04
Epoch 73/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2718 - mae: 0.3614 - mse: 0.2528 - r2_score: 0.7294 - val_loss: 0.2243 - val_mae: 0.3141 - val_mse: 0.2054 - val_r2_score: 0.7761 - learning_rate: 1.2500e-04
Epoch 74/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2734 - mae: 0.3617 - mse: 0.2545 - r2_score: 0.7267 - val_loss: 0.2240 - val_mae: 0.3120 - val_mse: 0.2052 - val_r2_score: 0.7765 - learning_rate: 1.2500e-04
Epoch 75/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2744 - mae: 0.3616 - mse: 0.2557 - r2_score: 0.7281 - val_loss: 0.2224 - val_mae: 0.3110 - val_mse: 0.2038 - val_r2_score: 0.7797 - learning_rate: 1.2500e-04
Epoch 76/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2723 - mae: 0.3609 - mse: 0.2537 - r2_score: 0.7277 - val_loss: 0.2232 - val_mae: 0.3126 - val_mse: 0.2047 - val_r2_score: 0.7779 - learning_rate: 1.2500e-04
Epoch 77/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2737 - mae: 0.3631 - mse: 0.2552 - r2_score: 0.7233 - val_loss: 0.2253 - val_mae: 0.3109 - val_mse: 0.2068 - val_r2_score: 0.7754 - learning_rate: 1.2500e-04
Epoch 78/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2707 - mae: 0.3587 - mse: 0.2523 - r2_score: 0.7318 - val_loss: 0.2236 - val_mae: 0.3111 - val_mse: 0.2053 - val_r2_score: 0.7767 - learning_rate: 1.2500e-04
Epoch 79/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2662 - mae: 0.3549 - mse: 0.2479 - r2_score: 0.7371 - val_loss: 0.2213 - val_mae: 0.3086 - val_mse: 0.2031 - val_r2_score: 0.7796 - learning_rate: 1.2500e-04
Epoch 80/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.2605 - mae: 0.3518 - mse: 0.2423 - r2_score: 0.7419 - val_loss: 0.2262 - val_mae: 0.3144 - val_mse: 0.2080 - val_r2_score: 0.7733 - learning_rate: 1.2500e-04
Epoch 81/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2724 - mae: 0.3602 - mse: 0.2543 - r2_score: 0.7293 - val_loss: 0.2238 - val_mae: 0.3130 - val_mse: 0.2057 - val_r2_score: 0.7768 - learning_rate: 1.2500e-04
Epoch 82/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2753 - mae: 0.3638 - mse: 0.2573 - r2_score: 0.7224 - val_loss: 0.2237 - val_mae: 0.3139 - val_mse: 0.2057 - val_r2_score: 0.7758 - learning_rate: 1.2500e-04
Epoch 83/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2666 - mae: 0.3572 - mse: 0.2486 - r2_score: 0.7353 - val_loss: 0.2217 - val_mae: 0.3104 - val_mse: 0.2038 - val_r2_score: 0.7790 - learning_rate: 1.2500e-04
Epoch 84/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2649 - mae: 0.3568 - mse: 0.2470 - r2_score: 0.7355 - val_loss: 0.2207 - val_mae: 0.3101 - val_mse: 0.2029 - val_r2_score: 0.7792 - learning_rate: 1.2500e-04
Epoch 85/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.2640 - mae: 0.3556 - mse: 0.2462 - r2_score: 0.7392 - val_loss: 0.2229 - val_mae: 0.3081 - val_mse: 0.2052 - val_r2_score: 0.7763 - learning_rate: 1.2500e-04
Epoch 86/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2631 - mae: 0.3552 - mse: 0.2454 - r2_score: 0.7382 - val_loss: 0.2264 - val_mae: 0.3151 - val_mse: 0.2088 - val_r2_score: 0.7729 - learning_rate: 1.2500e-04
Epoch 87/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2676 - mae: 0.3576 - mse: 0.2500 - r2_score: 0.7314 - val_loss: 0.2227 - val_mae: 0.3141 - val_mse: 0.2051 - val_r2_score: 0.7768 - learning_rate: 1.2500e-04
Epoch 88/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.2650 - mae: 0.3568 - mse: 0.2475 - r2_score: 0.7345 - val_loss: 0.2213 - val_mae: 0.3108 - val_mse: 0.2038 - val_r2_score: 0.7794 - learning_rate: 1.2500e-04
Epoch 89/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2708 - mae: 0.3635 - mse: 0.2533 - r2_score: 0.7260 - val_loss: 0.2241 - val_mae: 0.3107 - val_mse: 0.2067 - val_r2_score: 0.7758 - learning_rate: 1.2500e-04
Epoch 90/100
390/390 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2656 - mae: 0.3566 - mse: 0.2482 - r2_score: 0.7289 - val_loss: 0.2203 - val_mae: 0.3090 - val_mse: 0.2029 - val_r2_score: 0.7790 - learning_rate: 6.2500e-05
Epoch 91/100

In [45]:
def plot_hist(history):
    hist = pd.DataFrame(history.history)
    hist['epoch'] = history.epoch
    hist['rmse'] = np.sqrt(hist['mse'])

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=hist['epoch'], y=hist['mae'], name='mae', mode='markers+lines'))
    fig.add_trace(go.Scatter(x=hist['epoch'], y=hist['val_mae'], name='val_mae', mode='markers+lines'))
    fig.update_layout(width=1000, height=500, title='MAE vs. VAL_MAE', xaxis_title='Epoki', yaxis_title='Mean Absolute Error', yaxis_type='log')
    fig.show()

plot_hist(history)

In [46]:
test_loss, test_mae, _, _ = model.evaluate(X_test, y_test)

print("Test MSE:", test_loss)
print("Test MAE:", test_mae)

122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2349 - mae: 0.3175 - mse: 0.2181 - r2_score: 0.7727
Test MSE: 0.23492148518562317
Test MAE: 0.31746605038642883

In [47]:
from sklearn.metrics import r2_score

predictions = model.predict(X_test)

r2 = r2_score(y_test, predictions)
print("R2:", r2)

122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
R2: 0.7858785465312974

In [48]:
# poprawa danych - cofniecie skalowania
predictions = model.predict(X_test).flatten()

# cofnięcie skalowania
predictions_real = y_scaler.inverse_transform(predictions.reshape(-1,1)).flatten()
y_test_real = y_scaler.inverse_transform(y_test).flatten()

results = pd.DataFrame({
    "rzeczywiste": y_test_real,
    "przewidywane": predictions_real,
    "błąd": abs(predictions_real - y_test_real)
})

results.head()

122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

    rzeczywiste  przewidywane         błąd
0  96200.000000 112501.140625 16301.140625
1 178700.000000 203692.093750 24992.093750
2  60600.000000  74308.039062 13708.039062
3 191900.000000 178050.750000 13849.250000
4  51000.000000  56234.523438  5234.523438

In [49]:
fig = px.scatter(results, x='rzeczywiste', y='przewidywane')
fig.add_trace(go.Scatter(x=[0, 500000], y=[0, 500000], mode='lines'))
fig.show()

RandomForestRegressor

In [50]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import (mean_squared_error, mean_absolute_error, r2_score)

In [51]:
rf = RandomForestRegressor(random_state=42)

In [52]:
param_dist = {
    "n_estimators": [100, 200, 300, 500],
    "max_depth": [10, 20, 30, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": ["sqrt", "log2"]
}

In [53]:
random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions = param_dist,
    n_iter = 20, # liczba losowych kombinacji
    cv = 5,
    scoring="r2",
    verbose=2,
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train, y_train) # 5 * 20 = 100 kombinacji

Fitting 5 folds for each of 20 candidates, totalling 100 fits

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning:

A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'max_depth': [10, 20, 30, None],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 200, 300, 500]},
                   random_state=42, scoring='r2', verbose=2)

In [54]:
print("Najlepsze parametry:", random_search.best_params_)
print("Najlepszy wynik R2:", random_search.best_score_)

Najlepsze parametry: {'n_estimators': 200, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'max_depth': 30}
Najlepszy wynik R2: 0.7768543200019292

In [55]:
best_rf = random_search.best_estimator_

predictions_rf = best_rf.predict(X_test)

In [56]:
print("MSE:", mean_squared_error(y_test, predictions_rf))
print("MAE:", mean_absolute_error(y_test, predictions_rf))
print("R2:", r2_score(y_test, predictions_rf))

MSE: 0.21286996075827266
MAE: 0.3146792244665789
R2: 0.7909791686337703

In [57]:
predictions = model.predict(X_test)

# cofnięcie skalowania y
predictions = y_scaler.inverse_transform(predictions).flatten()
y_true = y_scaler.inverse_transform(y_test).flatten()

results = pd.DataFrame({
    "rzeczywiste": y_true,
    "przewidywane": predictions,
    "błąd": predictions - y_true
})

fig = px.scatter(results, x="rzeczywiste", y="przewidywane")

fig.add_trace(
    go.Scatter(
        x=[0, 500000],
        y=[0, 500000],
        mode="lines",
        name="Idealne dopasowanie",
        line=dict(color="red")
    )
)

fig.show()

122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step





# Porównanie modeli

| Model                 | MAE   | MSE   | R^2    |
|----------------------|-------|-------|-------|
| Prosta sieć neuronowa | 0.3516 | 0.2539 | 0.7507 |
| Ulepszona sieć NN     | 0.3175 | 0.2349 | 0.7859 |
| RandomForest          | 0.3147 | 0.2129 | 0.7910 |

Wraz z rozbudową architektury sieci neuronowej następowała stopniowa poprawa jakości predykcji.

Dodanie Batch Normalization, Dropout, regularyzacji L2 oraz Early Stopping zmniejszyło błąd predykcji i poprawiło zdolność modelu do uogólniania.

Nie zaobserwowano przeuczenia, ponieważ zarówno błąd treningowy, jak i walidacyjny zmniejszały się równolegle.

Najlepsze wyniki uzyskał jednak model Random Forest.

Uzyskany współczynnik R^2 = 0.791 oznacza, że model wyjaśnia około 79% zmienności cen mieszkań występujących w zbiorze danych.

Lepszy wynik Random Forest wynika z faktu, że dane mają charakter tabelaryczny. Modele drzewiaste bardzo dobrze odnajdują nieliniowe zależności oraz interakcje pomiędzy cechami, nie wymagając przy tym skomplikowanego procesu uczenia charakterystycznego dla sieci neuronowych.

Wnioski

Projekt pokazał pełny proces budowy modeli regresyjnych:
- przygotowanie danych,
- budowę podstawowej sieci neuronowej,
- zastosowanie technik poprawiających jakość uczenia,
- analizę metryk jakości,
- ocenę zjawiska overfittingu,
- porównanie z klasycznym modelem uczenia maszynowego,
- strojenie hiperparametrów.